apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.registry.ingress.certificateClusterIssuerName }}
    ingress.kubernetes.io/ssl-redirect: "true"
  {{- with .Values.registry.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: registry
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.registry.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "kube-image-keeper.fullname" . }}-registry
            port:
              number: 5000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.registry.ingress.host }}
    secretName: {{ include "kube-image-keeper.fullname" . }}-registry
